/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 32
#define YY_END_OF_BUFFER 33
static yyconst short int yy_accept[310] =
    {   0,
        0,    0,   33,   31,    1,   17,   29,   31,   29,   11,
       31,   25,   26,   29,   29,   29,   29,   29,   23,   23,
       29,   24,   29,   20,    7,   22,   31,   29,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   27,   29,   28,    1,   31,
        1,   29,    0,   18,    0,    0,    0,    0,    0,    0,
       23,    0,    0,   21,    0,    0,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   19,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,    1,    0,    0,    0,    0,    0,
        0,   30,   23,    0,   23,   23,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,    9,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,    0,   30,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,    0,
       22,   22,   22,   22,   22,   22,   22,   22,   22,    0,
       12,   16,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
        4,   22,   22,   22,   22,   22,   19,   22,   22,    0,
       22,   22,   10,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   19,   22,   19,   22,   22,   22,    0,
       22,   22,    0,   22,   22,   22,   22,   22,   22,   22,
       22,   19,   22,   13,   22,   22,   22,   22,    0,   22,
        0,   22,   22,   22,   22,   14,   22,   22,   22,   19,
        0,    0,   22,   22,    5,   19,   22,   22,    0,    6,
        0,    0,    0,   22,    0,   15,   22,   22,    0,    0,
       22,    8,   22,    0,    2,    8,   22,    0,   22,    0,

       22,    0,   22,    0,    0,    0,    0,    3,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   28,   28,   28,   29,   28,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   31,   30,   30,
       32,   33,   34,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   30,   30,   46,   47,   48,
       49,   50,   30,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        1,    1,    1,    1,    5,    1,    1,    6,    6,    7,
        7,    1,    1,    1,    1,    7,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[319] =
    {   0,
        0,   62,  461,  462,  458,  462,  435,   60,  434,   57,
       57,  445,  462,  432,   55,  462,   58,   60,   68,   72,
      434,  462,   47,  430,   51,    0,  419,  428,  397,  401,
       58,   45,   54,   69,   64,  395,   80,   22,   54,  407,
       71,   82,  395,   82,  402,  462,   74,  462,  126,   94,
      443,  462,  105,  462,  441,  109,  440,  429,  434,  117,
      124,  131,    0,  462,  416,  415,    0,  385,  388,  383,
      398,  397,  385,  386,  377,  382,  377,  378,  379,  377,
      374,  379,    0,  370,  369,  374,  364,  378,  372,  376,
      375,  103,  377,   77,  355,  109,  366,  361,  353,  360,

      364,  357,  109,  362,  155,  154,  156,  358,  392,  386,
      396,  395,  143,  147,  149,    0,  352,  354,  360,  347,
      345,  344,  354,  356,  356,  351,  345,  353,  352,  347,
      350,  345,    0,  328,  338,  332,  331,  326,  327,  333,
      330,  323,  335,  322,  353,  119,  323,  323,  330,  322,
      316,  328,  330,  320,  326,  462,  320,  311,  309,  308,
      314,  312,  313,  311,  303,  307,  316,  301,  313,  301,
      313,  298,  311,  306,  301,  292,  293,  294,  297,  320,
      292,  300,  292,  281,  130,  293,  281,  281,  292,  286,
        0,  135,  290,  289,  284,  289,  287,  280,  275,  283,

      270,  269,  276,  267,  280,  279,  276,  268,  273,  275,
      462,  270,  259,  274,  269,  272,  306,  270,  261,  251,
      265,  246,    0,  263,  256,  259,  262,  248,  246,  247,
      255,  253,  240,  271,  240,  254,  236,  246,  240,  157,
      240,  239,  244,  246,  230,  240,  222,  235,  217,  213,
      217,  225,  188,  462,  178,  188,  185,  184,  187,  182,
      181,  169,  169,  180,  177,  462,  177,  165,  178,  172,
      167,  173,  160,  175,  209,  189,  168,  156,  175,  462,
      166,  177,    0,  154,  202,  462,  150,  149,  145,  169,
      140,    0,  156,  141,  462,    0,  151,  152,  151,  148,

      134,  144,  130,  180,  178,  128,   40,  462,  462,  230,
      237,  241,  248,  255,  259,  265,  271,  275
    } ;

static yyconst short int yy_def[319] =
    {   0,
      309,    1,  309,  309,  309,  309,  309,  310,  309,  309,
      311,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  312,  309,  309,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  309,  309,  309,  309,  309,
      309,  309,  310,  309,  310,  311,  311,  313,  314,  309,
      309,  309,  315,  309,  309,  309,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  309,  309,  309,  309,  313,  313,
      314,  314,  309,  309,  309,  315,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  309,  309,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  309,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  309,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      309,  312,  312,  312,  312,  312,  312,  312,  312,  309,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  309,
      312,  312,  309,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  309,  312,  312,  312,  312,  309,  312,
      309,  312,  312,  312,  312,  309,  312,  312,  312,  312,
      309,  309,  312,  312,  312,  312,  312,  312,  309,  309,
      309,  309,  316,  312,  317,  309,  312,  312,  309,  316,
      312,  318,  312,  309,  309,  318,  312,  309,  312,  309,

      312,  309,  312,  309,  309,  309,  309,  309,    0,  309,
      309,  309,  309,  309,  309,  309,  309,  309
    } ;

static yyconst short int yy_nxt[526] =
    {   0,
        4,    5,    6,    7,    8,    4,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   16,   18,   19,   20,
       21,   22,   23,   24,   25,   16,   16,   26,   26,   26,
       26,   27,    4,    4,   28,   26,   29,   30,   31,   32,
       33,   34,   26,   26,   35,   26,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   26,   26,   26,   46,
       47,   48,   16,   49,   54,   52,   54,   50,   52,   65,
       52,   90,   58,   52,   52,   66,   91,   59,   52,  308,
       52,   52,   52,   52,   60,   74,   61,   61,   60,   57,
       61,   61,   55,   75,   70,  107,   62,   52,   63,   77,

       62,   71,   76,   72,   92,   83,   73,   93,   62,   54,
       78,   84,   62,   79,   80,   95,   86,   81,   54,   82,
       87,  141,   97,   96,   63,   98,  102,  105,   88,  142,
      103,  106,   99,   89,   52,  113,  113,   55,  108,  100,
       60,   57,   61,   61,  114,  144,  114,  138,  145,  115,
      115,  139,   62,  152,  153,  107,  105,  107,  240,  146,
      106,  113,  113,  181,   62,  115,  115,  115,  115,  215,
      221,   62,  182,  279,  282,  222,  279,  216,  282,  305,
      307,  305,   83,   62,  304,  303,  302,  301,  300,  299,
      298,  297,   83,  295,  280,  283,  294,  280,  108,  283,

      108,   83,  293,  285,  259,  291,  289,  288,  287,  286,
      285,  284,   83,  281,  278,  277,  276,  275,  274,   83,
      273,  272,   83,  271,   83,  270,  269,  268,  267,  306,
       53,   53,   53,   53,   53,   53,   53,   56,   56,   56,
       56,   56,   56,   56,   67,  266,   67,   67,  109,  109,
      109,  109,  109,  109,  109,  111,  111,   83,  111,  111,
      111,  111,  116,   83,  116,  290,  290,  290,  290,   83,
      290,  290,  292,  265,   83,  264,  292,  292,  296,  263,
      296,  296,  262,  261,  260,   83,  258,   83,  257,  256,
      255,  254,  253,  252,  251,  250,   83,  249,  248,   83,

      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,   83,   83,  236,   83,   83,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,   83,  225,  224,   83,
      223,  220,   83,  219,  218,  217,   83,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  197,   83,   83,  196,  195,  194,
      193,  192,  191,   83,  190,  189,  188,   83,  187,  186,
      185,  184,  183,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,   83,  162,  161,  160,  159,  158,   83,  157,   83,

       83,  112,  112,  156,  110,  155,  154,  151,  150,  149,
       83,  148,  147,  143,  140,  137,  136,  135,  134,  133,
      132,  131,   83,  130,   83,  129,  128,  127,  126,  125,
      124,  123,  122,  121,  120,  119,  118,  117,   52,   52,
      112,  110,  309,  309,   51,  104,  101,   94,   85,   69,
       68,   52,   52,   52,   64,   52,   52,   52,   52,   51,
      309,    3,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309
    } ;

static yyconst short int yy_chk[526] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    8,   10,   11,    2,   15,   23,
       23,   38,   18,   17,   25,   25,   38,   18,   15,  307,
       10,   17,   17,   18,   19,   32,   19,   19,   20,   11,
       20,   20,    8,   32,   31,   50,   19,   47,   19,   33,

       20,   31,   32,   31,   39,   35,   31,   39,   19,   53,
       33,   35,   20,   34,   34,   41,   37,   34,   56,   34,
       37,   94,   42,   41,   19,   42,   44,   49,   37,   94,
       44,   49,   42,   37,   47,   60,   60,   53,   50,   42,
       61,   56,   61,   61,   62,   96,   62,   92,   96,   62,
       62,   92,   61,  103,  103,  106,  105,  107,  240,   96,
      105,  113,  113,  146,   61,  114,  114,  115,  115,  185,
      192,  113,  146,  270,  272,  192,  279,  185,  282,  305,
      306,  304,  303,  113,  302,  301,  300,  299,  298,  297,
      294,  293,  291,  290,  270,  272,  289,  279,  106,  282,

      107,  288,  287,  285,  240,  284,  281,  278,  277,  276,
      275,  274,  273,  271,  269,  268,  267,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  253,  305,
      310,  310,  310,  310,  310,  310,  310,  311,  311,  311,
      311,  311,  311,  311,  312,  252,  312,  312,  313,  313,
      313,  313,  313,  313,  313,  314,  314,  251,  314,  314,
      314,  314,  315,  250,  315,  316,  316,  316,  316,  249,
      316,  316,  317,  248,  247,  246,  317,  317,  318,  245,
      318,  318,  244,  243,  242,  241,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,

      225,  224,  222,  221,  220,  219,  218,  217,  216,  215,
      214,  213,  212,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  190,  189,  188,  187,  186,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  145,  144,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  134,  132,  131,  130,  129,  128,
      127,  126,  125,  124,  123,  122,  121,  120,  119,  118,

      117,  112,  111,  110,  109,  108,  104,  102,  101,  100,
       99,   98,   97,   95,   93,   91,   90,   89,   88,   87,
       86,   85,   84,   82,   81,   80,   79,   78,   77,   76,
       75,   74,   73,   72,   71,   70,   69,   68,   66,   65,
       59,   58,   57,   55,   51,   45,   43,   40,   36,   30,
       29,   28,   27,   24,   21,   14,   12,    9,    7,    5,
        3,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex_cpp.l"
#define INITIAL 0
#line 2 "lex_cpp.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

FILE *output;
FILE *error_output;

int semicolon_expected = 0;
int errors = 0;
int line_number = 1;
int in_declaration = 0;
int in_class = 0;
char current_type[50] = "";
char current_var[50] = "";
char current_class[50] = "";
int expecting_value = 0;
int access_specifier = 0;  // 0: private, 1: public, 2: protected
int in_namespace_std = 0;  // Track if 'using namespace std' is active
int in_template = 0;      // Track if we're in a template declaration
int in_function = 0;
int expecting_colon = 0;
char current_scope[50] = "global";
int has_iostream = 0;
int has_string = 0;

#define MAX_VARS 1000
#define MAX_STD_SYMBOLS 100
#define MAX_STD_HEADERS 20

typedef struct {
    char name[50];
    char type[50];
    int is_initialized;
    int line_declared;
    char class_name[50];  // For class members
    int is_const;
    int access_level;     // 0: private, 1: public, 2: protected
    int is_template;      // Whether this is a template type
    char scope[50];        // Added for scope tracking
} Variable;

Variable vars[MAX_VARS];
int var_count = 0;

// Standard library headers
char std_headers[MAX_STD_HEADERS][50] = {
    "iostream", "string", "vector", "map", "set",
    "algorithm", "memory", "utility", "cmath", "cstdlib",
    "ctime", "fstream", "sstream", "iomanip", "array",
    "deque", "queue", "stack", "list", "bitset"
};

// Standard library symbols
char std_symbols[MAX_STD_SYMBOLS][50] = {
    // IO streams
    "cout", "cin", "cerr", "clog", "endl", "flush", "ws",
    // String operations
    "string", "getline", "to_string", "stoi", "stol", "stof", "stod",
    // Containers
    "vector", "map", "set", "list", "queue", "stack", "deque", 
    "pair", "array", "forward_list", "multiset", "multimap",
    "unordered_map", "unordered_set", "priority_queue", "bitset",
    // Algorithms
    "sort", "find", "reverse", "count", "max", "min", "swap",
    // Memory
    "shared_ptr", "unique_ptr", "weak_ptr", "make_shared", "make_unique",
    // Types
    "size_t", "string_view", "nullptr_t", "initializer_list",
    // Stream types
    "ostream", "istream", "fstream", "stringstream", "ofstream", "ifstream",
    // Additional common symbols
    "begin", "end", "rbegin", "rend", "push_back", "pop_back", "emplace_back",
    "insert", "erase", "clear", "size", "empty", "front", "back"
};

void add_std_symbols() {
    if (in_namespace_std) {
        for(int i = 0; i < MAX_STD_SYMBOLS; i++) {
            if(strlen(std_symbols[i]) > 0) {
                strcpy(vars[var_count].name, std_symbols[i]);
                strcpy(vars[var_count].type, "std");
                vars[var_count].is_initialized = 1;
                strcpy(vars[var_count].scope, "global");
                var_count++;
            }
        }
    }
}

void add_var(const char *var, const char *type) {
    // Don't add if it's already in std namespace
    if(in_namespace_std) {
        for(int i = 0; i < MAX_STD_SYMBOLS; i++) {
            if(strcmp(std_symbols[i], var) == 0) {
                return;
            }
        }
    }

    // Check for redefinition
    for (int i = 0; i < var_count; i++) {
        if (strcmp(vars[i].name, var) == 0) {
            return;  // Allow redefinition in C++
        }
    }

    if (var_count < MAX_VARS) {
        strcpy(vars[var_count].name, var);
        strcpy(vars[var_count].type, type);
        vars[var_count].is_initialized = 1;
        vars[var_count].line_declared = line_number;
        strcpy(vars[var_count].class_name, current_class);
        vars[var_count].access_level = access_specifier;
        var_count++;
    }
}

Variable* get_var(const char *var) {
    // Check if using iostream without include
    if (!has_iostream && (strcmp(var, "cout") == 0 || strcmp(var, "endl") == 0 || strcmp(var, "cin") == 0)) {
        fprintf(error_output, "Line %d: Using iostream symbols without #include <iostream>\n", line_number);
        errors++;
        return NULL;
    }

    // Check if using string without include
    if (!has_string && strcmp(var, "string") == 0) {
        fprintf(error_output, "Line %d: Using string without #include <string>\n", line_number);
        errors++;
        return NULL;
    }

    // Check if it's a standard symbol and we're using namespace std
    if(in_namespace_std) {
        for(int i = 0; i < MAX_STD_SYMBOLS; i++) {
            if(strcmp(std_symbols[i], var) == 0) {
                return NULL;  // Allow use of std symbols
            }
        }
    }

    // Check if it's a std:: qualified name
    char std_prefix[] = "std::";
    if (strncmp(var, std_prefix, strlen(std_prefix)) == 0) {
        const char *symbol = var + strlen(std_prefix);
        for(int i = 0; i < MAX_STD_SYMBOLS; i++) {
            if(strcmp(std_symbols[i], symbol) == 0) {
                return NULL;  // Allow use of std:: qualified symbols
            }
        }
    }

    // Check variables in current scope
    for (int i = 0; i < var_count; i++) {
        if (strcmp(vars[i].name, var) == 0) {
            return &vars[i];
        }
    }

    // If we get here and the symbol is in std but we're not using namespace std
    for(int i = 0; i < MAX_STD_SYMBOLS; i++) {
        if(strcmp(std_symbols[i], var) == 0) {
            fprintf(error_output, "Line %d: '%s' is not declared. Did you forget 'using namespace std' or 'std::'?\n", 
                line_number, var);
            errors++;
            return NULL;
        }
    }

    fprintf(error_output, "Line %d: Undeclared identifier '%s'\n", line_number, var);
    errors++;
    return NULL;
}

void check_type_mismatch(const char *value) {
    if (current_var[0] != '\0') {
        Variable *v = get_var(current_var);
        if (v != NULL) {
            if (strcmp(v->type, "int") == 0 || strcmp(v->type, "float") == 0 || 
                strcmp(v->type, "double") == 0) {
                if (value[0] == '"') {
                    fprintf(error_output, "Line %d: Type mismatch - Cannot assign string to %s variable '%s'\n", 
                        line_number, v->type, current_var);
                    errors++;
                }
            }
            if (v->is_const && v->is_initialized) {
                fprintf(error_output, "Line %d: Assignment to const variable '%s'\n", 
                    line_number, current_var);
                errors++;
            }
            v->is_initialized = 1;
        }
    }
}

void check_access_violation(const char *var) {
    Variable *v = get_var(var);
    if (v != NULL && strlen(v->class_name) > 0) {
        if (v->access_level == 0) {  // private
            fprintf(error_output, "Line %d: Accessing private member '%s'\n", line_number, var);
            errors++;
        }
    }
}

#line 794 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 234 "lex_cpp.l"


#line 951 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 310 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 462 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 236 "lex_cpp.l"
{ /* skip whitespace */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 238 "lex_cpp.l"
{
                fprintf(output, "Include directive: %s (Line %d)\n", yytext, line_number);
                if (strstr(yytext, "<iostream>")) {
                    has_iostream = 1;
                }
                if (strstr(yytext, "<string>")) {
                    has_string = 1;
                }
            }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 248 "lex_cpp.l"
{
                    fprintf(output, "Using namespace std (Line %d)\n", line_number);
                    in_namespace_std = 1;
                    add_std_symbols();
                }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 254 "lex_cpp.l"
{
                    fprintf(output, "Std Namespace Access (Line %d)\n", line_number);
                }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 258 "lex_cpp.l"
{
                    fprintf(output, "Namespace Keyword (Line %d)\n", line_number);
                }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 262 "lex_cpp.l"
{
                    fprintf(output, "Template Declaration Start (Line %d)\n", line_number);
                }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 266 "lex_cpp.l"
{
                    fprintf(output, "Template Declaration End (Line %d)\n", line_number);
                }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 270 "lex_cpp.l"
{
                    fprintf(output, "Namespace Declaration (Line %d)\n", line_number);
                }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 274 "lex_cpp.l"
{
                    fprintf(output, "Dynamic Memory Allocation (Line %d)\n", line_number);
                }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 278 "lex_cpp.l"
{
                    fprintf(output, "Dynamic Memory Deallocation (Line %d)\n", line_number);
                }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 282 "lex_cpp.l"
{
                    fprintf(output, "Reference Type (Line %d)\n", line_number);
                    strcat(current_type, "&");
                }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 287 "lex_cpp.l"
{
                    fprintf(output, "Class Declaration (Line %d)\n", line_number);
                    in_class = 1;
                    access_specifier = 0;  // default is private
                }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 293 "lex_cpp.l"
{
                    fprintf(output, "Public Access Specifier (Line %d)\n", line_number);
                    access_specifier = 1;
                }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 298 "lex_cpp.l"
{
                    fprintf(output, "Private Access Specifier (Line %d)\n", line_number);
                    access_specifier = 0;
                }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 303 "lex_cpp.l"
{
                    fprintf(output, "Protected Access Specifier (Line %d)\n", line_number);
                    access_specifier = 2;
                }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 308 "lex_cpp.l"
{
                    fprintf(output, "Const Qualifier (Line %d)\n", line_number);
                    strcat(current_type, "const ");
                }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 313 "lex_cpp.l"
{
                    if (semicolon_expected) {
                        fprintf(error_output, "Line %d: Missing semicolon\n", line_number);
                        semicolon_expected = 0;
                        errors++;
                    }
                    fprintf(output, "Line Number: %d\n", line_number++);
                    in_declaration = 0;
                }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 323 "lex_cpp.l"
{ 
                    fprintf(output, "String Literal: %s (Line %d)\n", yytext, line_number);
                    if (expecting_value) {
                        check_type_mismatch(yytext);
                        expecting_value = 0;
                    }
                }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 331 "lex_cpp.l"
{
                    fprintf(output, "Keyword: %s (Line %d)\n", yytext, line_number);
                    if (strcmp(yytext, "class") != 0 && strcmp(yytext, "public") != 0 && 
                        strcmp(yytext, "private") != 0 && strcmp(yytext, "protected") != 0 &&
                        strcmp(yytext, "const") != 0) {
                        strcpy(current_type, yytext);
                        in_declaration = 1;
                    }
                }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 341 "lex_cpp.l"
{
                    fprintf(output, "Assignment Operator: = (Line %d)\n", line_number);
                    expecting_value = 1;
                }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 346 "lex_cpp.l"
{
                    fprintf(output, "Scope Resolution Operator (Line %d)\n", line_number);
                }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 350 "lex_cpp.l"
{
                    fprintf(output, "Identifier: %s (Line %d)\n", yytext, line_number);
                    if (in_declaration) {
                        add_var(yytext, current_type);
                        strcpy(current_var, yytext);
                    } else {
                        Variable *v = get_var(yytext);
                        if (!v) {
                            fprintf(error_output, "Line %d: Undeclared identifier '%s'\n", line_number, yytext);
                            errors++;
                        } else {
                            check_access_violation(yytext);
                        }
                        strcpy(current_var, yytext);
                    }
                }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 367 "lex_cpp.l"
{ 
                    fprintf(output, "Number: %s (Line %d)\n", yytext, line_number);
                    if (expecting_value) {
                        expecting_value = 0;
                    }
                }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 374 "lex_cpp.l"
{ 
                    fprintf(output, "Semicolon Detected (Line %d)\n", line_number);
                    semicolon_expected = 0;
                    in_declaration = 0;
                    expecting_value = 0;
                    strcpy(current_var, "");
                }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 382 "lex_cpp.l"
{ fprintf(output, "Left Parenthesis (Line %d)\n", line_number); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 383 "lex_cpp.l"
{ fprintf(output, "Right Parenthesis (Line %d)\n", line_number); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 384 "lex_cpp.l"
{ fprintf(output, "Left Brace (Line %d)\n", line_number); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 385 "lex_cpp.l"
{ 
                    fprintf(output, "Right Brace (Line %d)\n", line_number);
                    if (in_class) {
                        in_class = 0;
                        strcpy(current_class, "");
                    }
                }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 393 "lex_cpp.l"
{
                    fprintf(output, "Operator: %s (Line %d)\n", yytext, line_number);
                }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 397 "lex_cpp.l"
{
                    fprintf(output, "Comment: %s (Line %d)\n", yytext, line_number);
                }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 401 "lex_cpp.l"
{ fprintf(output, "Unknown Token: %s (Line %d)\n", yytext, line_number); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 403 "lex_cpp.l"
ECHO;
	YY_BREAK
#line 1303 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 310 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 310 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 309);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 403 "lex_cpp.l"


int main(int argc, char *argv[]) {
    if (argc < 2) {
        printf("Usage: %s <input_file>\n", argv[0]);
        return 1;
    }

    FILE *input = fopen(argv[1], "r");
    if (!input) {
        perror("Error opening input file");
        return 1;
    }

    output = fopen("output/result.txt", "w");
    error_output = fopen("output/errors.txt", "w");

    if (!output || !error_output) {
        perror("Error opening output files");
        fclose(input);
        return 1;
    }

    yyin = input;
    yylex();

    fprintf(output, "\n--- End of Token List ---\n");
    fprintf(error_output, "\n--- End of Compile-Time Error Report ---\n");

    fclose(input);
    fclose(output);
    fclose(error_output);

    return 0;
}
